### ISSUE TITLE
Revive the project

### ISSUE THREAD

**Issue by Veetaha** [matklad/tom#26]
Hey, I'd like to try getting involved into this project mainly for the benefit of rust-analyzer.

@matklad would you be able to review or at least approve and merge prs here? Also, do you have any ideas on how to integrate this with `ra`?

Just some thoughts on high-level architecture:
 I think we can expose smth like ~~`ra_ide`~~ `tom_ide` API and add this crate as a dependency to `rust-analyzer` binary.

Also, it seems like we should avoid Cargo.toml specificity here, but I'd like to actually provide features for this specific case (like adding hints for packages versions ala [vscode crates extension](https://www.google.com/url?sa=t&source=web&rct=j&url=https://marketplace.visualstudio.com/items%3FitemName%3Dserayuzgur.crates&ved=2ahUKEwiEmq6Zp9DpAhUOHHcKHZ2tBoIQFjAAegQIBBAC&usg=AOvVaw2urnjysiJEtafSq7KYOwH1)). It's hard to think how we could achieve this if we want to abstract from toml files content semantic interpretation. Or do you think adding such a feature here (maybe behind `features = ["cargo_toml"]`) wont be bad?

Also could you please take a quick rereview of the issues here to close potentially no-longer actual ones?

**Comment by matklad** [comment]
Send invite!

Realistically, I don't think I'll be able to review PRs here (like, I don't think I can properly review PRs in rust-analyzer any more :) )

I guess my plan to make something useful of tom would be:

* strictly focus on IDE side of things
* kill all the semantic bits (they are hugely complex and are a design molasses)
* strictly focus on Cargo.toml format (I think it would be easier to generlize once we get something out of the door)
* modernize code base (switch to new rowan, rewrite lexer, remove as much code as possible, make sure that what's left makes sense)
* build an independent langauge-server VS Code plugin, for Cargo.toml specifically (should allow to iterate faster)
* after plugin works, merge the code with rust-analyzer. Ie, either make `rust-analyzer` handle both `Cargo.toml` and `*.rs`, or add `rust-analyzer toml-lsp` command which spawns an independent server.

**Comment by Veetaha** [comment]
@matklad thanks for the trust, I hope I'll be able to keep the spirit and the experience of `ra` here.

I'd like to consult, anyway:
* What semantic bits do you imply? Because, you know, providing `cargo.toml`-specific features requires semantic interpretation
* I hope to extract and share the lexer from [`toml-rs`](https://github.com/alexcrichton/toml-rs/blob/master/src/tokens.rs) instead of rewriting it here (you have changed your mind on regexp parsing huh :D?).
* I wonder if it's appropriate to integrate `salsa` here. I'd like to play with that )

**Comment by matklad** [comment]
Semantic bits: https://github.com/matklad/tom/blob/master/src/model.rs. I belive this should die, and, at least initially, we should just use the syntactic info without too much of an abstraction on top. 

>hope to extract and share the lexer from toml-rs instead of rewriting it here (you have changed your mind on regexp parsing huh :D?).

Seems good. I don't think my options about lexing shifted significantly recently (~after I've learned about tree sitter). I still belive that parsing and lexing are two different things and should not be confused. I still that lexer, generated from a set of regexes, is the right tool for the job(so, rustc_lexer is wrong). m_lexer is right conceptually (the model is correct), but it's a runtime model  and not a compile time model.

>I wonder if it's appropriate to integrate salsa here. I'd like to play with that )

No :)

**Comment by Veetaha** [comment]
> I belive this should die, and, at least initially, we should just use the syntactic info without too much of an abstraction on top.

Right, I guess it is rather the field of responsibility of `toml-rs` here, I'll see if this is really avoidable...

> Realistically, I don't think I'll be able to review PRs here

Thanks, I'll be merging my PRs, without your review than...

> No :)

Okay, you know better

**Comment by Veetaha** [comment]
@matklad 
Fun fact:
turns out there was a [JavaScript dependency trying to steal your bitcoins :D](https://stackoverflow.com/a/53578285/9259330)
Trying to install the dependencies in `lsp/code` threw this at me:
```
~/dev/tom/lsp/code (feat/migrate-to-rust-analyzer-like-project-structure) $ npm i
npm WARN tom-lsp@0.0.1 No description
npm WARN tom-lsp@0.0.1 No license field.

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
npm ERR! 404 
npm ERR! 404  'event-stream@3.3.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'code'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm WARN tar ENOENT: no such file or directory, open '/home/veetaha/dev/tom/lsp/code/node_modules/.staging/typescript-a9644c73/lib/typescript.d.ts'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/veetaha/.npm/_logs/2020-05-26T21_13_03_067Z-debug.log
~/dev/tom/lsp/code (feat/migrate-to-rust-analyzer-like-project-structure) $ 
```

**Comment by Veetaha** [comment]
Also, I am not sure about the naming. I moved the code under `crates/tom` and `crates/tom_lsp_server`.
I am not sure whether we should rename `tom` -> `tom_syntax`

**Comment by Veetaha** [comment]
@matklad may I ask you to give me `bors r+` permissions in this repo, pretty please?

**Comment by matklad** [comment]
Fixed

**Comment by Veetaha** [comment]
Unfortunately, I got involved in a different private project most of my time, and won't be able to contribute to `tom` in foreseeable future =(
